### ISSUE TITLE
USER STORY: Hero Image

### ISSUE THREAD

**Issue by Duffew** [Duffew/love-running#3]
As a **web user**, I want to be able to **quickly understand what the site is about**, so that **I know if it's relevant to me**.

## Acceptance Criteria
+ Criteria 1: Hero image is colourful
+ Criteria 2: Hero image shows what the activity is about
+ Criteria 3: Hero image grabs my attention

## Tasks
- [ ] Task 1: Select several images
- [ ] Task 2: Get user feedback on the best one
- [ ] Task 3: Add to home page

#1
